### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@EyalIlan any idea what's wrong here? Why build is failing?

**Comment by shaked-hayek** [comment]
@atalyaalon did you add the new "NATUN-LOGO-FINAL-COLOR.png" file in the commit? I'm not seeing it

**Comment by atalyaalon** [comment]
@shaked-hayek I added it in a pr before - you can see it here: https://github.com/data-for-change/anyway-newsflash-infographics/blob/dev/src/assets/NATUN-LOGO-FINAL-COLOR.png

Maybe @EyalIlan has insights since he played with it a little as well and locally it worked for him

**Comment by atalyaalon** [comment]
@EyalIlan @shaked-hayek I'm trying to merge

**Pull request merged**
