### PR TITLE
yaxis added

### PR DESCRIPTION
**Pull request by SejoB**
image

### CODE REVIEW

**Comment by atalyaalon** [comment]
@MichalOren @galraij what do you think of this change?

**Comment by MichalOren** [comment]
Thanks @SejoB This is a great job (: 
I would like to understand regarding the **Reference Line**, that according to the specification, should appear in the background of the graph (#1050). Is there a problem implementing them ?? 
Their importance is reflected in two use cases:
1. When you want to download the graph as an image and then there is no tip tool (no number at all)
2. In case you choose an 8-year display, then the information is dense and hard to read, the reference line can make it more readable.

**Comment by atalyaalon** [comment]
@MichalOren we can add a Grid, no problem in that, however @SejoB and I thought it would not look good (so news sites won't necessarily want to use it)
If you and @galraij want to add a grid it's

**Comment by MichalOren** [comment]
Hi @SejoB @atalyaalon @galraij  
Can you recomend on any other indication that will give the user more info?
According to my check N12 are using Reference Line. For example:
image
I think this is clear and nice display
Would you like to share with us an example

**Pull request merged**
